<br />
<br />

<form method="POST">
    <label for="code">Код</label>
    <input id="code" name="code" type="text"><br />

    <label for="author">Автор</label>
    <input id="author" name="author" type="text"><br />

    <label for="price">Ціна</label>
    <input id="price" name="price" type="number"><br />

    <label for="score">Оцінки</label>
    <input id="score" name="score" type="text" placeholder="Вводити оцінки через кому без пробілу *(4,4,4)"><br />

    <button type="submit">Добавити</button>
</form>