GET localhost:3005
Accept: application/json

###
GET localhost:3005/1
Accept: application/json

###
GET localhost:3005/logs
Accept: application/json
###
GET localhost:3005/computers
Accept: application/json

###
GET localhost:3005/computers/1
Accept: application/json

###
DELETE localhost:3005/remove/id/1
Accept: application/json

###
DELETE localhost:3005/remove/surname/Hal
Accept: application/json

###
PATCH localhost:3005/1
Content-Type: application/json

{
  "surname": "Hal_1",
  "room_num": 16,
  "group_name": "Front-end WebDev",
  "pc_id": 1
}

###
PATCH localhost:3005/computers/1
Content-Type: application/json

{
  "gpu": "RTX 4090 TI",
  "cpu": "i9-9400F",
  "ram": 32
}

###
POST localhost:3005/computers
Content-Type: application/json

{
  "gpu": "GTX-1660 TUF OC",
  "cpu": "I-5 9400F",
  "ram": 8
}

###
POST localhost:3005/
Content-Type: application/json

{
  "surname": "Hal",
  "room_num": 16,
  "group_name": "Front-end WebDev",
  "pc_id": 1
}

###